### ISSUE TITLE
Minicharts without R

### ISSUE THREAD

**Issue by hairpin666** [rte-antares-rpackage/leaflet.minicharts#22]
Hi,

Is it possible to use this plugin without R? 

I"d like to create minicharts on top of a normal map included in a webpage not running R.

Thanks and best regards

**Comment by bthieurmel** [comment]
Hi,

Of course ! You can use this plugin directly in javascript using ``leaflet.js`` and ``minicharts.js`` : 

https://github.com/rte-antares-rpackage/minicharts

**Comment by FrancoisGuillem** [comment]
Hello,

If you know some javascript you can use the leaflet plugin [leaflet.minichart](https://github.com/rte-antares-rpackage/leaflet.minichart). 

If you don't or don't want to, you can create your map in R, you can save it  as a webpage using `htmlwidgets::saveWidget()` or the "export" button in Rstudio. Then you can integrate it in your webpage.

**Comment by hairpin666** [comment]
Great thanks, for the links, I think I'll go with the leaflet plugin.

**Comment by jalazawa** [comment]
I think @hairpin666 solved his problem. I close this issue.
