### ISSUE TITLE
syncWith() does not work anymore

### ISSUE THREAD

**Issue by FrancoisGuillem** [rte-antares-rpackage/leaflet.minicharts#27]
https://github.com/rstudio/leaflet/issues/347

**Comment by FrancoisGuillem** [comment]
@bthieurmel Te souviens-tu pourquoi tu as commenté ce bout de cod dans syncWith.js:

```js
// Bug with leafet > 1, & no really need...?
    /*self.on("move", function() {
      LeafletWidget.syncGroups.sync(self, groupname);
    });*/
```
J'ai décommenté et ça a l'air de fonctionner correctement

**Comment by bthieurmel** [comment]
Il y avait des plantages avec ``leafet > 1``, et donc le package ``leaflet > 2.0.0``.

Je n'arrive pas à les reproduire après plusieurs tests donc je viens de le décommenter....

**Comment by bthieurmel** [comment]
@jalazawa : tu es le maintener. Tu peux faire le nécessaire ?
