### ISSUE TITLE
Error in abs(data) : non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by kuzmenkov111** [rte-antares-rpackage/leaflet.minicharts#9]
Thank you for GREAT package! There is some problem, when minicharts uses for bilding pie chart data frame with one row (one geographical point)

**Comment by FrancoisGuillem** [comment]
Thank you for the feedback. It looks like this bug does not exist anymore in the last development version. You can install it with:

```r
devtools::install_github("rte-antares-rpackage/leaflet.minicharts", ref = "develop")
```

**Comment by kuzmenkov111** [comment]
Thank you. It works, but only in Rstudio viewer (leaflet map). In shiny app it does not work (table with one row)- chart (pie) does not appear. And there is not any error in console.

**Comment by FrancoisGuillem** [comment]
This is strange. Could you share some code to reproduce the problem?

**Comment by kuzmenkov111** [comment]
Its ok. I find some css, which blocked pie chart (table with one row) on map.
